
fn main {
  // let context = @llvm.Context::create();
  // let lmodule = context.create_module("demo");
  // let i32_ty = context.i32_type();
  // let f32_ty = context.f32_type();
  // let f64_ty = context.f64_type();
  // let bool_ty = context.bool_type();
  // let void_ty = context.void_type();
  // let fty = void_ty.fn_type_unsafe([
  //   context.i32_type().as_type_ref(),
  //   context.i32_type().as_type_ref(),
  //   context.f32_type().as_type_ref(),
  //   context.f32_type().as_type_ref(),
  //   context.f64_type().as_type_ref(),
  //   context.f64_type().as_type_ref(),
  // ]);
  // // fty.dump()
  // println(fty)
}
