// /**
//  * @defgroup LLVMCInitialization Initialization Routines
//  * @ingroup LLVMC
//  *
//  * This module contains routines used to initialize the LLVM system.
//  *
//  * @{
//  */
//
// void LLVMInitializeCore(LLVMPassRegistryRef R);
// void LLVMInitializeTransformUtils(LLVMPassRegistryRef R);
// void LLVMInitializeScalarOpts(LLVMPassRegistryRef R);
// void LLVMInitializeVectorization(LLVMPassRegistryRef R);
// void LLVMInitializeInstCombine(LLVMPassRegistryRef R);
// void LLVMInitializeIPO(LLVMPassRegistryRef R);
// void LLVMInitializeAnalysis(LLVMPassRegistryRef R);
// void LLVMInitializeIPA(LLVMPassRegistryRef R);
// void LLVMInitializeCodeGen(LLVMPassRegistryRef R);
// void LLVMInitializeTarget(LLVMPassRegistryRef R);
